### ISSUE TITLE
Link to PyFFI submodule seems dead.

### ISSUE THREAD

**Issue by Ghostbird** [niftools/blender_nif_plugin#208]
I needed the submodule (obviously) however when I tried to get it:

```
blender_nif_plugin$ git submodule update --init --recursive
Cloning into 'pyffi'...
fatal: unable to connect to git.code.sf.net:
git.code.sf.net[0: 216.34.181.155]: errno=Connection refused

Clone of 'git://git.code.sf.net/p/pyffi/code' into submodule path 'pyffi' failed
```

**Comment by Ghostwalker71** [comment]
I believe that link pulls from sourceforge which is currently down and has been for several days. The development branch pulls from the niftools git repo, or should.

**Comment by neomonkeus** [comment]
It did, but I reverted those changes you made as requested

**Comment by Ghostwalker71** [comment]
As a general rule we always use recursive clone, but the blender plugin has a critical failure due to the index from pyffi being corrupt and hanging on the kfm.xml sub-module. It is fixed in the develop branch but several factors have prevented that fix from being merged to master.
@neomonkeus I remember only the one revert for the develop branch and I immediately sent a new pull to reapply the changes cleanly, I am sure the develop branch is pointing to  the git repo now. though master is still pointing at sourceforge.

**Comment by neomonkeus** [comment]
https://github.com/niftools/blender_nif_plugin/blob/develop/.gitmodules

**Comment by Ghostwalker71** [comment]
hmph, I was sure I changed that. oh well, if I find the time I will send a pull.

**Comment by psi29a** [comment]
I updated this in my commit: https://github.com/niftools/blender_nif_plugin/pull/255

.gitmodule now points to github repo.

https://github.com/niftools/blender_nif_plugin/pull/255/commits/be4415e006db85582918e0f22e6791cbc217cf8e
