### ISSUE TITLE
Is there any guides on how to install?

### ISSUE THREAD

**Issue by SigHoovestrong** [niftools/blender_nif_plugin#269]
Hey am posting here cause just don't know where else to go with my issue. At moment having problem finding a guide and help when come to install this this plugin for blender i insure you my version is currently 2.79. I been looking among the file for while no if included read through how set up all the things but find none. LIke for all i know be doing thing corract just going into blender preferences installing it from there. But some other issue may accure but i have no way telling if doing things the corract way begin with. Cause well. I have no guide. Maybe there is read through somewhere but just not found it. IN any case very unclear to me what am suppose to do. Anyhow just having something i could read trought would be huge help and maybe come to whatever conclusion on why i just not able to make this plugin to work.

**Comment by Ghostwalker71** [comment]
https://www.youtube.com/watch?v=2RvLZvX_rsI Here is a good video tutorial on the install procedure. it is for 2.69 but the install process is the same.

**Comment by L0FKA** [comment]
@Ghostwalker71 Is it true that your github commit history = current state of development of the plugin ? 🤔 

p.s.
wazzup

**Comment by Ghostwalker71** [comment]
Howdy @L0FKA, It's nice to see you around. As far as I am aware there hasn't been any updates to the plugin, other than documentation, since I left the project. I could be wrong though. I haven't been paying much attention to it. I just check in every so often to see if it has reached a usable state for games I tend to mod.
I saw a few commits that appeared to be geared toward automation of builds. Though when I left the project I was in the middle of coding the export function for the more difficult skyrim files as well as trying to get a handle on the fallout files and I am fairly sure some of the experimental code ended up getting merged so it wasn't in a working state.

**Comment by SigHoovestrong** [comment]
Thanks i'll check that out.

**Comment by neomonkeus** [comment]
The plugin doesn't support Blender 2.79 due to API changes.
