### ISSUE TITLE
Rigged meshes with "Scene Root" in their name end up with wrong parent and transforms

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [niftools/blender_nif_plugin#373]
@niftools/blender-nif-plugin-reviewer

# Issue Overview
Super weird, I suspect this is due to pyffi but I'm not sure.

### Blender Nif Plugin Version Info
dev

### Blender Version Info
2.81+

### Platform information
[Provide a brief overview of what OS your running on]

## Context
[Provide more detailed information to the issue itself and why it is relevant]

## Steps to Reproduce
Open attached blend file, export as is -> bug
Rename mesh objects so they don't have "scene root" in their name -> works fine

## Expected Result
[Describe what you expected to have resulted from this process]

## Actual Result
[Describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix
[Optional, suggest fixes, improvement or reasons for the bug might have occurred]

## Screenshot
[If relevant, include a screenshot]

## Logs and Files
[Provide logs file generated during the error as well as the blend and nif files are related to the issue]

### Info Bar Output
[Output from the Info View, available at top of Blender viewport, drag to expand]

### Console Output
[Set the logging level to 'Debug' and attach the output of the console. Enable via Window -> Toggle Console]

### Blend File
[Attach the blend file if the issue is reproducible]

### Nif File
[nif dev.zip](https://github.com/niftools/blender_nif_plugin/files/4936394/nif.dev.zip)

## Similar Known Issues
[Reference any known issues - https://github.com/niftools/blender_nif_plugin/issues]

## Additional Information
[Anything else you feel is relevant]

**Comment by HENDRIX-ZT2** [comment]
There's no apparent mention of "Scene Root" in the plugin codebase. So I think it could be a pyffi issue...

**Comment by Ghostwalker71** [comment]
Is the transform happening on import or export? Most of the bethesda games use scene root as the base of the rigged meshes. There is a specific section of the armature export code that dealt with making sure that became the root during export, I had updated it while adding code for skyrim so that it would still apply the scene root as the root for the games that used scene root but would not apply it to those that no longer used that. It isn't applied in pyffi, but I think it does cycle some things through pyffi so if there is a disconnect with the recent reorganization of the code it will likely be in the armature import/export sections rather than in pyffi.

**Comment by HENDRIX-ZT2** [comment]
It's on export. The mesh is parented to the armature (not bone) but ends up attached to some child node of the armature if 'scene root' is in the name of the mesh.

**Comment by Ghostwalker71** [comment]
Alright that is almost definitely happening in the code I added during the skyrim update, most likely the sanity check is no longer catching and isn't stopping the code before it adds a new scene root node to the mesh. unfortunately the layout of everything has changed enough that you would likely be able to find it before I could. Though if you would like, I can try to dig through and look it over.
